### ISSUE TITLE
Investigate passing in web3provider to prompt for metamask/wallet txs

### ISSUE THREAD

**Issue by aryabhuptani** [connext/vector-modal#13]
Right now, users need to manually deposit to the channel address, even in cases like DG where they are using metamask. However, we definitely don't want to *exclude* cases like PM where users typically will not have wallets and will be sending from exchanges.

Perhaps a happy intermediate solution is to allow for passing in a web3provider into the widget -- if one is passed in, the widget can automatically prompt user for a deposit.

Another issue to consider here is what happens in the case where the dapp uses a web3 wallet like Magic, but that's not actually where the users funds are? Additionally -- how do we know much to deposit in the first place? We'll need to investigate these questions a bit more deeply by asking users what kind of flow works best for them.

**Comment by rhlsthrm** [comment]
Primary implementation complete:
- `injectedProvider` as modal prop.
- Ask the user for the deposit amount.
- Check amount against router balance before initiating user tx.
