### ISSUE TITLE
Clarify in docs that you need to get API keys for RPCs like infura/alchemy

### ISSUE THREAD

**Issue by aryabhuptani** [connext/vector-modal#15]
The example currently does not include this which caused some confusion

**Comment by rhlsthrm** [comment]
The docs here: https://app.archbee.io/docs/R6w14eIlq8wdqU9likOX_/un-IUm2QFi2_oakW2lvw7 do specify that the chainProviders need to be Infura/Alchemy or ETH node URLs.

**Comment by rhlsthrm** [comment]
Closing for now.
