### ISSUE TITLE
Allow received amount to be edited, should change transferred amount

### ISSUE THREAD

**Issue by rhlsthrm** [connext/vector-modal#54]
Refer to Uniswap: https://www.loom.com/share/a545c1847dca4dbcb7b88ab9e286965d

Requires design changes as well as Vector changes.

**Comment by rhlsthrm** [comment]
https://www.figma.com/file/zA2765zAInt3QQetwNvRla/Connext-Widget-UI?node-id=0%3A1

Designs ^^.

Blocked by https://github.com/connext/vector/issues/422

**Comment by LayneHaber** [comment]
Required updates have been released for the vector core packages

**Comment by sanchaymittal** [comment]
Done
