### ISSUE TITLE
Handle cookies error

### ISSUE THREAD

**Issue by LayneHaber** [connext/vector-modal#56]
If there are issues connecting to the browser node due to cookies not being available, users should be clearly prompted to enable cookies. Here is an [example](https://cdn.discordapp.com/attachments/813914092707905546/818533269476868146/unknown.png) of the current display

**Comment by sanchaymittal** [comment]
Handling this here: https://github.com/connext/vector-modal/blob/main/src/components/Modal.tsx#L986
