### ISSUE TITLE
Restore if cannot sync

### ISSUE THREAD

**Issue by LayneHaber** [connext/vector-modal#69]
We should catch this error and then restore the state and retry the transfer/update, specifically the `Cannot sync, must restore` bit. Once this is done we need to update DG since they have a user with a channel in this state.

![image](https://user-images.githubusercontent.com/12769011/111243159-312d4000-85c6-11eb-9ca1-1ec8c36962bd.png)

**Comment by rhlsthrm** [comment]
OK the issue here is that we handle the case where you can lose your store completely. However we don't handle the case where you can advance state in one browser and come back to another browser and try to advance the state which is now out of sync.
