### ISSUE TITLE
Incomplete error at reconcile deposit

### ISSUE THREAD

**Issue by sanchaymittal** [connext/vector-modal#76]
![Screenshot 2021-03-17 at 1 04 15 PM](https://user-images.githubusercontent.com/31698676/111431044-48cd0b80-8721-11eb-90de-980f06cc1b9a.png)

Error is incomplete to apply, sync update at vector modal.
And Ideally we should keep this at vector modal considering this could became a blocker for matic wallet too.

**Comment by rhlsthrm** [comment]
I tried to reproduce this with Sanchay's key. I got a different error that fixed itself after a retry. I believe this particular error is fixed.
