### ISSUE TITLE
Handle Metamask wallet switches while modal is open

### ISSUE THREAD

**Issue by rhlsthrm** [connext/vector-modal#78]
Right now it doesn't switch to detect new balance.

**Comment by sanchaymittal** [comment]
@rhlsthrm switching metamask to new balance is a little tricky, Cause Dapps use same loginProvider and webProvider, so we have to refresh it from the start.

We can detect the change in signer address and refresh the modal if it helps.

**Comment by sanchaymittal** [comment]
@rhlsthrm this is known problem in space, https://github.com/ChainSafe/web3.js/issues/3585
still waiting for this to be implemented
