### ISSUE TITLE
Handle sender cancels better

### ISSUE THREAD

**Issue by LayneHaber** [connext/vector-modal#81]
If a user is using the same account on two different browsers, then they could end up with one having an out of sync store that includes an already-cancelled sender transfer. This means that when they come online in the out-of-sync browser they will wait indefinitely for a sender transfer to be cancelled.

To fix this, we should call `reconcileDeposit` and restore if necessary *before* performing the cleanup tasks

**Comment by rhlsthrm** [comment]
Done.
