### ISSUE TITLE
Option to disable QR code

### ISSUE THREAD

**Issue by rhlsthrm** [connext/vector-modal#84]
There are use cases where the dapp itself will handle the initial user deposit (i.e. through a meta-tx). In those cases, we need to disable the QR code, change the "Show me QR Code" text to just "Swap", and the next screen should be a "Waiting" screen while the dapp is handling the process of sending the tx.

**Comment by georgeroman** [comment]
Any estimates on when this will land?

**Comment by sanchaymittal** [comment]
>Replied on personal message on discord
